version: '3.8'

services:
  jiwonbot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: jiwonbot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./images:/app/images:ro
    depends_on:
      - database
    networks:
      - bot_network

  database:
    image: postgres:15-alpine
    container_name: jiwonbot_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=jiwonbot
      - POSTGRES_USER=${DB_USER:-jiwonbot}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  db_data:
    driver: local